format_version: v1.0
type: UniqueComponent
attributes: {id: drv_sst26}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: DRV_SST26_HEADER_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/sqi_flash/sst26/templates/drv_sst26_qspi_definitions.h.ftl}
  - type: Integer
    attributes: {id: DRV_SST26_NUM_BUFFER_DESC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: '32'}
  - type: String
    attributes: {id: DRV_SST26_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: QSPI}
  - type: Combo
    attributes: {id: DRV_SST26_PROTOCOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: SQI}
  - type: File
    attributes: {id: DRV_SST26_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/sqi_flash/sst26/src/drv_sst26_qspi.c}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_sst26_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: drv_sst26_SQI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: qspi}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: QSPI_SQI}
  - type: DirectCapability
    attributes: {id: memory}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: serial_mem_bootloader}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: btl_MEMORY_dependency_SERIAL}
- type: ElementPosition
  attributes: {x: '160', y: '167', id: drv_sst26}
