package:
  format-version: "1.0.0"
  name: "bootloader_apps_serial_memory"
  version: "v3.2.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bootloader"
      type: "package"
      version: "v3.7.0"