format_version: v1.0
type: UniqueComponent
attributes: {id: uart2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '216'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '0'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '100000000'}
  - type: File
    attributes: {id: UART_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/uart_02478/templates/plib_uart_ring_buffer.h.ftl}
  - type: Boolean
    attributes: {id: UART_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: 'true'}
  - type: KeyValueSet
    attributes: {id: UART_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: 'true'}
  - type: Comment
    attributes: {id: UART_RING_BUFFER_SIZE_CONFIG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: UART_RX_RING_BUFFER_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: UART_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/uart_02478/templates/plib_uart_ring_buffer.c.ftl}
  - type: Integer
    attributes: {id: UART_TX_RING_BUFFER_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '8'}
- type: ElementPosition
  attributes: {x: '19', y: '280', id: uart2}
