format_version: v1.0
type: UniqueComponent
attributes: {id: serial_mem_bootloader}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BTL_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: '16384'}
  - type: String
    attributes: {id: DRIVER_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: DRV_SST26}
  - type: String
    attributes: {id: MEM_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: NVM}
  - type: Boolean
    attributes: {id: SERIAL_MEM_ERASE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: btl_MEMORY_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: nvm}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NVM_MEMORY}
  - type: DirectDependency
    attributes: {id: btl_MEMORY_dependency_SERIAL}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_sst26}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: memory}
- type: ElementPosition
  attributes: {x: '342', y: '138', id: serial_mem_bootloader}
