format_version: v1.0
type: UniqueComponent
attributes: {id: drv_sst26}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: DRV_SST26_HEADER_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/sqi_flash/sst26/templates/drv_sst26_sqi_definitions.h.ftl}
  - type: Integer
    attributes: {id: DRV_SST26_NUM_BUFFER_DESC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
  - type: String
    attributes: {id: DRV_SST26_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: SQI1}
  - type: Combo
    attributes: {id: DRV_SST26_PROTOCOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: SQI}
  - type: File
    attributes: {id: DRV_SST26_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/sqi_flash/sst26/src/drv_sst26_sqi.c.ftl}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_sst26_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: drv_sst26_SQI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sqi1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SQI1_SQI}
- type: ElementPosition
  attributes: {x: '141', y: '238', id: drv_sst26}
