format_version: v1.0
type: UniqueComponent
attributes: {id: drv_sst26}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: CHIP_SELECT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Chip Select 0}
  - type: Boolean
    attributes: {id: DRV_MEMORY_CONNECTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory_0, value: 'true'}
  - type: File
    attributes: {id: DRV_SST26_HEADER_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/sqi_flash/sst26/templates/drv_sst26_sqi_definitions.h.ftl}
  - type: Integer
    attributes: {id: DRV_SST26_NUM_BUFFER_DESC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
  - type: String
    attributes: {id: DRV_SST26_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: SQI1}
  - type: Combo
    attributes: {id: DRV_SST26_PROTOCOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: SQI}
  - type: File
    attributes: {id: DRV_SST26_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/sqi_flash/sst26/src/drv_sst26_sqi.c.ftl}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_sst26_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: drv_sst26_SQI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sqi1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SQI1_SQI}
  - type: DirectCapability
    attributes: {id: memory}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_memory_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_memory_MEMORY_dependency}
- type: ElementPosition
  attributes: {x: '147', y: '53', id: drv_sst26}
