format_version: v1.0
configName: qspi_bootloader_pic32cx_bz
folderName: qspi_bootloader_pic32cx_bz
frameworkPath: C:\Users\I76597\h3
processor: WBZ451
projectName: qspi_bootloader_pic32cx_bz
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CX-BZ_DFP\1.2.230\WBZ451\atdf\WBZ451.atdf
