files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: E756F4F8478D74EBC8E23B130954750D
  logicalPath: config/pic32mz_ef_curiosity_v2/bootloader
  name: bootloader.c
  physicalPath: bootloader
  security: NON_SECURE
  type: SOURCE
  userChecksum: E756F4F8478D74EBC8E23B130954750D
- generatedChecksum: 82184E6E6BF21D7C0E91DE0BD7609E90
  logicalPath: config/pic32mz_ef_curiosity_v2/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 82184E6E6BF21D7C0E91DE0BD7609E90
- generatedChecksum: A3E17273BDAD8A51FDF695EBF9AD9A77
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/hardware_access
  name: diskio.c
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: SOURCE
  userChecksum: A3E17273BDAD8A51FDF695EBF9AD9A77
- generatedChecksum: 257ACC61A57EA8DE78BA7E1F78DB85A3
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/memory
  name: drv_memory.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 257ACC61A57EA8DE78BA7E1F78DB85A3
- generatedChecksum: AD5CAAD66A56C9B5D17EB7E756C22D0C
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/memory
  name: drv_memory_file_system.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: AD5CAAD66A56C9B5D17EB7E756C22D0C
- generatedChecksum: 479D3F2FF6900275CD72549F38CD37F7
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/sst26
  name: drv_sst26.c
  physicalPath: driver/sst26/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 479D3F2FF6900275CD72549F38CD37F7
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: B2ADAD943E1B2BEEFF974468E2509BD5
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/file_system
  name: ff.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: B2ADAD943E1B2BEEFF974468E2509BD5
- generatedChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/file_system
  name: ffunicode.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
- generatedChecksum: E98F8C801E876DE3384FF2587F5BB877
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E98F8C801E876DE3384FF2587F5BB877
- generatedChecksum: BBF0D9D99B5764809C285383BA2C43C8
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BBF0D9D99B5764809C285383BA2C43C8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/cache
  name: plib_cache.c
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
- generatedChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/cache
  name: plib_cache_local.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
- generatedChecksum: 0DA10C8889278A796D0EE4C6096B57C3
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/cache
  name: plib_cache_pic32mz.S
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0DA10C8889278A796D0EE4C6096B57C3
- generatedChecksum: 1D681ED01F57EBA2D556EA541E5D6272
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1D681ED01F57EBA2D556EA541E5D6272
- generatedChecksum: AEEEEE203190423C2C13EE4EB96F909F
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: AEEEEE203190423C2C13EE4EB96F909F
- generatedChecksum: A70EEF6C533B6AA7F5CEC5E9954449D2
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A70EEF6C533B6AA7F5CEC5E9954449D2
- generatedChecksum: CA41C0116AA86AA82F796A658ADFE1E7
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA41C0116AA86AA82F796A658ADFE1E7
- generatedChecksum: A2E207D459736D20CF2C38D551EE1A99
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/sqi
  name: plib_sqi1.c
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: SOURCE
  userChecksum: A2E207D459736D20CF2C38D551EE1A99
- generatedChecksum: 47204A328D6218B0241B5993D3198668
  logicalPath: config/pic32mz_ef_curiosity_v2/system/cache
  name: sys_cache.c
  physicalPath: system/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47204A328D6218B0241B5993D3198668
- generatedChecksum: 71464A58B25E0CE05A50B07FC954C654
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs
  name: sys_fs.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71464A58B25E0CE05A50B07FC954C654
- generatedChecksum: C77DCE1A0DBF2C421E4DC73C7C34ACF6
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs
  name: sys_fs_fat_interface.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C77DCE1A0DBF2C421E4DC73C7C34ACF6
- generatedChecksum: 8A001811B92463BDE7B3A13B4A9E4BCE
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs
  name: sys_fs_media_manager.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8A001811B92463BDE7B3A13B4A9E4BCE
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_ef_curiosity_v2/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: D2B3E160AF8FBCAF6246D25D293520DE
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D2B3E160AF8FBCAF6246D25D293520DE
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mz_ef_curiosity_v2/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 5C6769BE2DE6D43EC80B53DAEB0374E2
  logicalPath: config/pic32mz_ef_curiosity_v2/bootloader
  name: bootloader.h
  physicalPath: bootloader
  security: NON_SECURE
  type: HEADER
  userChecksum: 5C6769BE2DE6D43EC80B53DAEB0374E2
- generatedChecksum: 3A3D90BBDFDB486B57C8FED3BA7D4135
  logicalPath: config/pic32mz_ef_curiosity_v2/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3A3D90BBDFDB486B57C8FED3BA7D4135
- generatedChecksum: 778BF17F952A2B9FD1F391330E58E89F
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 778BF17F952A2B9FD1F391330E58E89F
- generatedChecksum: 5EB68C5E4700E907866B7F28C99A23CF
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5EB68C5E4700E907866B7F28C99A23CF
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
- generatedChecksum: 630DFA1824A5279838B4330DA2FF3E5E
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/hardware_access
  name: diskio.h
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: HEADER
  userChecksum: 630DFA1824A5279838B4330DA2FF3E5E
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_ef_curiosity_v2/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_ef_curiosity_v2/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: EFD9CC847D820C0DCC84B3877B8FA415
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/memory
  name: drv_memory.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: EFD9CC847D820C0DCC84B3877B8FA415
- generatedChecksum: 8BF1EFFCD7DC02480C27F3DE35FB5009
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/memory
  name: drv_memory_definitions.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: 8BF1EFFCD7DC02480C27F3DE35FB5009
- generatedChecksum: 2E25CEFA28CCA2CD66BA9DF6B4C66621
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/memory
  name: drv_memory_local.h
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 2E25CEFA28CCA2CD66BA9DF6B4C66621
- generatedChecksum: 8EAE086FFBCC60C4343BAA26620B1204
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/sst26
  name: drv_sst26.h
  physicalPath: driver/sst26
  security: NON_SECURE
  type: HEADER
  userChecksum: 8EAE086FFBCC60C4343BAA26620B1204
- generatedChecksum: D712283D4ED135C84E162B40760A9C23
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/sst26
  name: drv_sst26_definitions.h
  physicalPath: driver/sst26
  security: NON_SECURE
  type: HEADER
  userChecksum: D712283D4ED135C84E162B40760A9C23
- generatedChecksum: D0F58EA0E69F1EC3040F9EB3C64B9737
  logicalPath: config/pic32mz_ef_curiosity_v2/driver/sst26
  name: drv_sst26_local.h
  physicalPath: driver/sst26/src
  security: NON_SECURE
  type: HEADER
  userChecksum: D0F58EA0E69F1EC3040F9EB3C64B9737
- generatedChecksum: 2D3A9FC37968F5000CB45C6B4AD965D6
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/file_system
  name: ff.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D3A9FC37968F5000CB45C6B4AD965D6
- generatedChecksum: 910609C7022F0F44C5B9B6E36B7C824D
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/file_system
  name: ffconf.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 910609C7022F0F44C5B9B6E36B7C824D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_ef_curiosity_v2/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_ef_curiosity_v2/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_ef_curiosity_v2/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 37885E3505BF5B0FD6AFE768807361C1
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/cache
  name: plib_cache.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 37885E3505BF5B0FD6AFE768807361C1
- generatedChecksum: 3D2558D7758EF020BBF792820203C0A2
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/cache
  name: plib_cache_pic32mz.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D2558D7758EF020BBF792820203C0A2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 815CCB981B6CB758464D89480121DC08
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 815CCB981B6CB758464D89480121DC08
- generatedChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
- generatedChecksum: 42ECD2217FBCF58E950E691EEB8D7E11
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: 42ECD2217FBCF58E950E691EEB8D7E11
- generatedChecksum: 83A29BB1714DD4AF71B7176C4A487262
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/sqi
  name: plib_sqi1.h
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: 83A29BB1714DD4AF71B7176C4A487262
- generatedChecksum: BA2AAEA19E581F59C1E78E73982F7C78
  logicalPath: config/pic32mz_ef_curiosity_v2/peripheral/sqi
  name: plib_sqi_common.h
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: BA2AAEA19E581F59C1E78E73982F7C78
- generatedChecksum: AFAAF7D896D57569CA4CF73BB3339481
  logicalPath: config/pic32mz_ef_curiosity_v2/system/cache
  name: sys_cache.h
  physicalPath: system/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: AFAAF7D896D57569CA4CF73BB3339481
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mz_ef_curiosity_v2/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: DDC1AA937FC332670372DC2E7B5CA1F2
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs
  name: sys_fs.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: DDC1AA937FC332670372DC2E7B5CA1F2
- generatedChecksum: 4E8B283AD5759C0A37157EB5ADEB9B81
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs
  name: sys_fs_fat_interface.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 4E8B283AD5759C0A37157EB5ADEB9B81
- generatedChecksum: 0D162D1868A187FDC092657020E668D8
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs
  name: sys_fs_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D162D1868A187FDC092657020E668D8
- generatedChecksum: D0DEC824B933722219A05F00A4CD5BB4
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs
  name: sys_fs_media_manager.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: D0DEC824B933722219A05F00A4CD5BB4
- generatedChecksum: E50782BD59B15F2EAAF53AAD818793EE
  logicalPath: config/pic32mz_ef_curiosity_v2/system/fs
  name: sys_fs_media_manager_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: E50782BD59B15F2EAAF53AAD818793EE
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_ef_curiosity_v2/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_ef_curiosity_v2/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_ef_curiosity_v2/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_ef_curiosity_v2/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: A1CB3454D5A9393479E09211BEEDDD49
  logicalPath: config/pic32mz_ef_curiosity_v2/system
  name: system_media.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: A1CB3454D5A9393479E09211BEEDDD49
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_ef_curiosity_v2/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config/pic32mz_ef_curiosity_v2
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 7F9FC2738C97030825C8BF3A2F2DC0B1
  logicalPath: ''
  name: btl.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 7F9FC2738C97030825C8BF3A2F2DC0B1
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_curiosity_v2;../src/packs/PIC32MZ2048EFM144_DFP;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/file_system;../src/config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/hardware_access
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32
  delimiter: ''
  key: optimization-level
  security: NON_SECURE
  value: -O2
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_curiosity_v2;../src/packs/PIC32MZ2048EFM144_DFP;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/file_system;../src/config/pic32mz_ef_curiosity_v2/system/fs/fat_fs/hardware_access
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
