format_version: v1.0
type: UniqueComponent
attributes: {id: drv_sst26}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: CHIP_SELECT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: CHIP_SELECT_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: DRV_SST26_HEADER_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/sqi_flash/sst26/templates/drv_sst26_sqi_definitions.h.ftl}
  - type: String
    attributes: {id: DRV_SST26_INTERFACE_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: SQI_PLIB}
  - type: Integer
    attributes: {id: DRV_SST26_NUM_BUFFER_DESC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: '64'}
  - type: String
    attributes: {id: DRV_SST26_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: SQI1}
  - type: Combo
    attributes: {id: DRV_SST26_PROTOCOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sst26, value: SQI}
  - type: File
    attributes: {id: DRV_SST26_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: driver/sqi_flash/sst26/src/drv_sst26_sqi_pic.c.ftl}
  - type: File
    attributes: {id: DRV_SST26_SPI_INTERFACE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: DRV_SST26_SPI_INTERFACE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: LANE_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_sst26_DRV_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: drv_sst26_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: drv_sst26_SQI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sqi1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SQI1_SQI}
  - type: DirectCapability
    attributes: {id: memory}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: serial_mem_bootloader}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: btl_MEMORY_dependency_SERIAL}
- type: ElementPosition
  attributes: {x: '170', y: '174', id: drv_sst26}
