format_version: v1.0
type: UniqueComponent
attributes: {id: qspi}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: QSPI_CPOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '0'}
  - type: KeyValueSet
    attributes: {id: QSPI_SMM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '0'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: QSPI_SPI}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: QSPI_SQI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_sst26}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_sst26_SQI_dependency}
- type: ElementPosition
  attributes: {x: '3', y: '202', id: qspi}
