configName: default
folderName: wbz351_curiosity
format_version: v1.0
frameworkPath: C:\h3
processor: WBZ351
projectName: wbz351_curiosity
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-BZ3_DFP\1.0.157
