format_version: v1.0
type: UniqueComponent
attributes: {id: serial_mem_bootloader}
children:
- type: Symbols
  children:
  - type: Setting
    attributes: {id: BOOTLOADER_XC32_LINKER_PREPROC_MARCOS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: ROM_LENGTH=0x2000;RAM_ORIGIN=0x20000000;RAM_LENGTH=0x8000}
  - type: String
    attributes: {id: BTL_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: '8192'}
  - type: String
    attributes: {id: DRIVER_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: DRV_AT25}
  - type: String
    attributes: {id: MEM_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: NVMCTRL}
  - type: Boolean
    attributes: {id: SERIAL_MEM_ERASE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: serial_mem_bootloader, value: 'false'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: btl_MEMORY_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: nvmctrl}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NVMCTRL_MEMORY}
  - type: DirectDependency
    attributes: {id: btl_MEMORY_dependency_SERIAL}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_at25}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: memory}
- type: ElementPosition
  attributes: {x: '310', y: '137', id: serial_mem_bootloader}
