configName: sam_e70_xult
folderName: sam_e70_xult
format_version: v1.0
frameworkPath: ..\..\..\..
processor: ATSAME70Q21B
projectName: qspi_programmer_app_sam_e70_xult
settings:
  PackageFilter: bootloader;bootloader_apps_can;bootloader_apps_ethernet;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_serial_memory;bootloader_apps_uart;bootloader_apps_usb;bsp;core;csp;net;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAME70_DFP\4.10.248
