files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_input.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: F74818AF60798C8B82255A88755ED9DA
  logicalPath: config/pic32mz_ef_sk/driver/sst26
  name: drv_sst26.c
  physicalPath: driver/sst26/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: F74818AF60798C8B82255A88755ED9DA
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 333E3BE52F82CFAF61F09BD889800DFB
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 333E3BE52F82CFAF61F09BD889800DFB
- generatedChecksum: BE2AD35B7B8C480DF070F25946D60B93
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BE2AD35B7B8C480DF070F25946D60B93
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 2DFA7367F1DFA82E5ADAB501A83ADD59
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2DFA7367F1DFA82E5ADAB501A83ADD59
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mz_ef_sk/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: ED048DB87E4B59467FD70AB52071EFCE
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED048DB87E4B59467FD70AB52071EFCE
- generatedChecksum: 085AD21E69A015135F99F9AE4E244A69
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 085AD21E69A015135F99F9AE4E244A69
- generatedChecksum: CA41C0116AA86AA82F796A658ADFE1E7
  logicalPath: config/pic32mz_ef_sk/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA41C0116AA86AA82F796A658ADFE1E7
- generatedChecksum: A2E207D459736D20CF2C38D551EE1A99
  logicalPath: config/pic32mz_ef_sk/peripheral/sqi
  name: plib_sqi1.c
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: SOURCE
  userChecksum: A2E207D459736D20CF2C38D551EE1A99
- generatedChecksum: 926DC70EA512413BC1A9E3AFEE574CAE
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 926DC70EA512413BC1A9E3AFEE574CAE
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 57406B1B24D79420C26D44C5625850A7
  logicalPath: config/pic32mz_ef_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 57406B1B24D79420C26D44C5625850A7
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_input.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: A9C595E0E5A92D2B85C18D2A27597B84
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: A9C595E0E5A92D2B85C18D2A27597B84
- generatedChecksum: A1211ED8D0E91DFCE92C2757F87F0E95
  logicalPath: config/pic32mz_ef_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: A1211ED8D0E91DFCE92C2757F87F0E95
- generatedChecksum: 65B33E66F3573CB06F86C01BCC9AC16F
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 65B33E66F3573CB06F86C01BCC9AC16F
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_ef_sk/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_ef_sk/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 8EAE086FFBCC60C4343BAA26620B1204
  logicalPath: config/pic32mz_ef_sk/driver/sst26
  name: drv_sst26.h
  physicalPath: driver/sst26
  security: NON_SECURE
  type: HEADER
  userChecksum: 8EAE086FFBCC60C4343BAA26620B1204
- generatedChecksum: D712283D4ED135C84E162B40760A9C23
  logicalPath: config/pic32mz_ef_sk/driver/sst26
  name: drv_sst26_definitions.h
  physicalPath: driver/sst26
  security: NON_SECURE
  type: HEADER
  userChecksum: D712283D4ED135C84E162B40760A9C23
- generatedChecksum: D0F58EA0E69F1EC3040F9EB3C64B9737
  logicalPath: config/pic32mz_ef_sk/driver/sst26
  name: drv_sst26_local.h
  physicalPath: driver/sst26/src
  security: NON_SECURE
  type: HEADER
  userChecksum: D0F58EA0E69F1EC3040F9EB3C64B9737
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: C28AA8F266DD056E96DCBE0761337241
  logicalPath: config/pic32mz_ef_sk/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: C28AA8F266DD056E96DCBE0761337241
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
- generatedChecksum: 42ECD2217FBCF58E950E691EEB8D7E11
  logicalPath: config/pic32mz_ef_sk/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: 42ECD2217FBCF58E950E691EEB8D7E11
- generatedChecksum: 83A29BB1714DD4AF71B7176C4A487262
  logicalPath: config/pic32mz_ef_sk/peripheral/sqi
  name: plib_sqi1.h
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: 83A29BB1714DD4AF71B7176C4A487262
- generatedChecksum: BA2AAEA19E581F59C1E78E73982F7C78
  logicalPath: config/pic32mz_ef_sk/peripheral/sqi
  name: plib_sqi_common.h
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: BA2AAEA19E581F59C1E78E73982F7C78
- generatedChecksum: 86D499749C924875389705AA3D0C9FD7
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 86D499749C924875389705AA3D0C9FD7
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mz_ef_sk/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_ef_sk/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_ef_sk/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_ef_sk/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config/pic32mz_ef_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;../src/packs/PIC32MZ2048EFH144_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;../src/packs/PIC32MZ2048EFH144_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
