configName: pic32mz_ef_curiosity_v2
folderName: pic32mz_ef_curiosity_v2
format_version: v1.0
frameworkPath: ..\..\..\..
processor: PIC32MZ2048EFM144
projectName: fs_qspi_flash_programmer_app_pic32mz_ef_curiosity_v2
settings:
  PackageFilter: bootloader;bootloader_apps_can;bootloader_apps_ethernet;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_serial_memory;bootloader_apps_uart;bootloader_apps_usb;bsp;core;csp;net;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MZ-EF_DFP\1.3.58
